title: Josh Nelson
description: Josh's personal site
baseurl: "" # the subpath of your site, e.g. /blog
url: "joshnelson.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Josh Nelson
author-image:   headshot.jpg
author-job:     IT Leader, strategist, closet coder
author-email:   josh@joshnelson.com # Add your email for contant form.
author-twitter: cloudappsguy # Add your twitter account
about-author:   I am long time technology industry veteran willing to lend an ear, offer advice, or talk about the weather. Understanding the 'Why' is important.

# Social settings
social-twitter:   cloudappsguy
social-facebook:
social-github:    cloudappsguy
social-pinterest: 
social-instagram: 
social-youtube:
social-vk:   
social-linkedin:  joshnelson

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
